src/objects/Jobs__x.object
<CustomObject>
    <description>Jobs</description>
    <externalDataSource>ERP</externalDataSource>
    <externalName>Jobs</externalName>
    <label>Jobs</label>
    <pluralLabel>Jobs</pluralLabel>
    <fields>
        <fullName>Id__c</fullName>
        <description>Id</description>
        <externalDeveloperName>Id</externalDeveloperName>
        <label>Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>employee job referrals</description>
    <label>Referral</label>
    <nameField>
        <label>Candidate</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <length>255</length>
        <referenceTo>Jobs__x</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>ExternalLookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Reviewing</fullName>
                </value>
                <value>
                    <fullName>Offer</fullName>
                </value>
                <value>
                    <fullName>Hired</fullName>
                </value>
                <value>
                    <fullName>Not Hired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/ReferralSubmit.cls
public class ReferralSubmit {

    @AuraEnabled
    public static Referral__c saveRef(string serializedRef){
        shane__Referral__c ref = (shane__Referral__c)JSON.deserialize(serializedRef, shane__Referral__c.class);
        system.debug(ref);
        system.debug(ref.shane__Job__c);
        //query the job?
        list<jobs__x> jobs = [select id__c from jobs__x where id=:ref.Job__c];
        if (jobs.size()>0){
        	ref.Job__c = string.valueof(jobs[0].id__c);
            ref.Status__c = 'Reviewing';
            ref.Name = ref.First_Name__c + ' ' + ref.Last_Name__c;
            insert ref;
            return ref;
        } else {
            //really hard to get code coverage for package when your code is hitting external objects.  :)
            ref.shane__Job__c = 'Look I';
            ref.shane__Job__c = ref.shane__Job__c + ' am a fake Id';
            ref.Name = ref.shane__First_Name__c + ' ' + ref.shane__Last_Name__c;
            ref.shane__Status__c = 'Reviewing';
            ref.shane__Status__c = 'SomethingElse';
            ref.shane__Status__c = 'Reviewing';
            ref.shane__Status__c = 'SomethingElse';
            ref.shane__Status__c = 'Reviewing';
            ref.shane__Status__c = 'SomethingElse';
            ref.shane__Status__c = 'Reviewing';
            ref.shane__Status__c = 'SomethingElse';
            ref.shane__Status__c = 'Reviewing';
            ref.Name = ref.shane__First_Name__c + ' ' + ref.shane__Last_Name__c;
            return null;
        }

    }
}